### ISSUE TITLE
Program Guide Page

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024#100]
We need a program guide page.

Ideally every year we've a [pdf version of program guide](https://drive.google.com/file/d/1tJhU8aUzafwE1t21ZlZj8gWuqJtR9Bke/view). However, we can perhaps build a better responsive program guide on web page.

The url needs to be `/program/` as it went on the badges as QR code already.

P.S. Not against pdf version. If that still like a better choice, can do it.

**Comment by palnabarun** [comment]
Don't worry about the link. I can reprogram /program to any URL.

**Comment by SaptakS** [comment]
**Priority: Add a link to the program guide**
Good to have: Add a Program Guide page

**Comment by SaptakS** [comment]
As discussed, might be good to have the styling print-friendly.

**Comment by SaptakS** [comment]
I think we can just add a link to the PDF that is being created.

**Comment by anistark** [comment]
we can render the pdf on the page ?

**Comment by SaptakS** [comment]
Yes, we can using some JS dependencies but I feel just making it download is better. Doesn't rely on internet to load the PDF once downloaded.

**Comment by palnabarun** [comment]
This is done
