### ISSUE TITLE
Restructure navigation

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2024#101]
This is what I am proposing:

- Logo which takes to homepage
- Schedule
- About
  - Team
  - FAQ
  - Health & Safety
  - Scholarships
  - DEI
  - Jobs Board
- Venue
  - About Venue
  - About Bengaluru
  - Accessibility
- Attend
  - Program Guide
  - Speakers
  - DevSprint
- Sponsors
- Code of Conduct
  - Our CoC Policy
  - Reporting Guidelines
- Blog

Please add/rearrange something if I missed anything.

**Comment by bhavin192** [comment]
Should Health & Safety, Scholarship be under Attend?
Maybe FAQ as well.

**Comment by SaptakS** [comment]
Actually I would probably like to rename "Attend" to "Talks" or "Programs". I wanted that to be the place for all the talks, lightning talks, devsprint, speaker, etc. information. Does that make sense?
