### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by rayandas** [pythonindia/inpycon2024#19]
The favicon is not visible for the website. We need to add it.

**Comment by Schefflera-Arboricola** [comment]
I think this is resolved(ref. ss below)

<img width="1440" alt="Screenshot 2024-04-29 at 9 04 09 PM" src="https://github.com/pythonindia/inpycon2024/assets/91629733/063aba7a-49fc-493f-a23e-6ab7d46a7b87">
