### ISSUE TITLE
Show contributors on readme file

### ISSUE THREAD

**Issue by bhansa** [pythonindia/inpycon2024#26]
There are some sites/plugins available which can show contributors data on readme file, it can be embedded on readme.

Example: https://github.com/HydPy/hydpyconf2019?tab=readme-ov-file#contributors- 

Any other suggestions are also welcomed.

**Comment by vamc-k** [comment]
@bhansa @devom-glitch 
I have added github-action to update contributors list in README file using python script.
Please check and review my PR #30

**Comment by bhansa** [comment]
Closed via #30
