### ISSUE TITLE
Remove duplicate instances of information

### ISSUE THREAD

**Issue by ramlaxman** [pythonindia/inpycon2024#33]
- [ ]  Remove text : 
>PyCon India 2024 is the premier conference for Python enthusiasts and professionals, offering an unparalleled opportunity to dive deep into the world of python and explore its limitless potentials.

- [ ] Tickets links: ![image](https://github.com/pythonindia/inpycon2024/assets/1982225/a0832d08-900a-4925-8e5b-9f9b84a1aa4c)

**Comment by kybrdbnd** [comment]
can i get some advice in here, what needs to be done

**Comment by ramlaxman** [comment]
Yes.
In my opinion:

- In the case of first task, we can remove the sentence appears twice on the website.
- In second case, I believe we can remove `buy tickets` button from website while `Tickets` at the right corner serves its purpose fully. :smile: 
Once you're done with these tasks, please push changes. 

- I'll update the tasks once we can come across with more duplicate information on the website.

@kybrdbnd Please feel free to comment tasks as duplicated ones so that volunteers can also work on it.

**Comment by bhansa** [comment]
- Instead of removing text lets propose alternate text which can work.
 - We don't need to remove the buy tickets button as that's the primary CTA for header and banner section, It should stay.

**Comment by ramlaxman** [comment]
CTA?

**Comment by bhansa** [comment]
[Call to action](https://en.wikipedia.org/wiki/Call_to_action_marketing)

**Comment by palnabarun** [comment]
Button doesn't exist on the site as Ticket sales are closed.
