### ISSUE TITLE
Update information on FAQ page

### ISSUE THREAD

**Issue by ramlaxman** [pythonindia/inpycon2024#35]
[FAQ](https://in.pycon.org/2024/faq/)
- [ ]  How to reach 
- [ ]  Sites to visit
- [ ]  Hotels to stay 
    - Recommended ones. If coming with family or solo.
- [ ]  Points to consider to make participants fully aware of details and feel safe to attend conference.

**Comment by kybrdbnd** [comment]
can i get details for these things

**Comment by bhansa** [comment]
We should create a travel page for this, similar to last year: https://in.pycon.org/2023/travel/

**Comment by anistark** [comment]
Covered in https://in.pycon.org/2024/bengaluru/ mostly.
