### ISSUE TITLE
Add Health and Safety Guidelines

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024#40]
We need to add a page for health and safety guidelines and a link to it from home page.

Examples:
- [PyCon US](https://us.pycon.org/2024/about/health-safety-guidelines/)
- [Djangocon US](https://2024.djangocon.us/public-health/)

**Comment by NavAneEth777** [comment]
where it should be added in the home page?

**Comment by sayanchowdhury** [comment]
https://pad.riseup.net/p/pyconindia2024-heath-safety -- please review this. 
Lazy consensus for Septmber 4th, 1800 IST

**Comment by anistark** [comment]
This is done.
