### ISSUE TITLE
Have ids for the headings on FAQ page

### ISSUE THREAD

**Issue by bhavin192** [pythonindia/inpycon2024#44]
We usually need to send specific FAQs to speakers and attendees. Having an id on all these headings would help with that. 
The ids don't need to be automatically generated, could be simple human readable, manually added ones as well.

I'm referring to the id attribute on the h tags. This will help to link to sections like `/faq/#buying-tickets`.

We will need this in coming week by Wednesday or so, as we send out acceptance emails to speakers. 

cc @bhansa

**Comment by bhansa** [comment]
Good idea! thanks for logging this issue @bhavin192. We will take it up this week.

**Comment by bhavin192** [comment]
Clarification: it would be preferable if we can link to a specific questions on that page. 

I just saw change you did on that page, that's what we need, but can we do some CSS change so it doesn't get highlighted as a link (blue and underline).

**Comment by bhansa** [comment]
Yeah, it is still under development. Will update once done.
