### ISSUE TITLE
About the Location

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024#74]
Add a page [about Bengaluru](https://github.com/pythonindia/inpycon2024/blob/main/src/bengaluru.md).

Covers:

- [ ] Reaching Bengaluru
- [ ] Transport in the city.
- [ ] Reaching the Venue.
- [ ] Places to stay recommendations.

(optional)
- [ ] Places to must visit
- [ ] Places to eat recommendations.

**Comment by kybrdbnd** [comment]
initial draft: https://docs.google.com/document/d/1yzwyiTugV3M_-V09eqdjURDitl-JDtcy/edit?usp=drive_link&ouid=105439413812836607015&rtpof=true&sd=true

Please review
