### ISSUE TITLE
Improving Bengaluru Page

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2024#78]
We've [everything about Bengaluru page](https://in.pycon.org/2024/bengaluru/). Suggestions on how and what to improve or fix welcome here...

**Comment by pratik-anurag** [comment]
- rename airport from Bengaluru International airport to Kempegowda International Airport Bengaluru

**Comment by pratik-anurag** [comment]
On similar lines, Bengaluru metro can be renamed as Namma Metro

**Comment by pratik-anurag** [comment]
Places to eat has Rameshwaram, can be renamed to Rameshwaram Cafe

**Comment by pratik-anurag** [comment]
Typo in Amintiti

**Comment by palnabarun** [comment]
1. DevSprints is an odd positioning over there.
2. There are no anchor elements.
