### ISSUE TITLE
Jobs Board

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2024#95]
Content:
- [ ] I think we need content for some introductory text?
- [ ] Integrate with a data file which the content team (or Jobs team) can then edit separately.

**Comment by anistark** [comment]
Can do a google form, for folks to enter job details.

Can attach it via sheet api to view directly. Ref: [2021 Job Board](https://in.pycon.org/2021/jobs/).

If there's a better way to do this, feel free to.

**Comment by bhansa** [comment]
@anistark please add Ritesh.

**Comment by RiteshAgrawal** [comment]
Assign to @bhansa as I won't be able to pick it up.
cc: @anistark

**Comment by bhansa** [comment]
Closed by #145
