### ISSUE TITLE
Venue Page

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2024#96]
@anistark Is the content for this page already available?

@vamc-k are you working on this?

**Comment by anistark** [comment]
Thought of using design like [this one](https://2024.ux-india.org/venue/).

We need to replace the existing [Bengaluru page](https://in.pycon.org/2024/bengaluru/). All content are there already.

This is more good to have though.

**Comment by SaptakS** [comment]
I think this is done mostly now. Closing.
